Variable	Definition

X:	Input dataset matrix where each row is a training example

y:	Output dataset matrix where each row is a training example

l0:	First Layer of the Network, specified by the input data

l1:	Second Layer of the Network, otherwise known as the hidden layer

l2:	Final Layer of the Network, which is our hypothesis, and should approximate the correct answer as we train.

syn0:	First layer of weights, Synapse 0, connecting l0 to l1.

syn1:	Second layer of weights, Synapse 1 connecting l1 to l2.

l2_error:	This is the amount that the neural network "missed".

l2_delta:	This is the error of the network scaled by the confidence. It's almost identical to the error except that very confident errors are muted.

l1_error:	Weighting l2_delta by the weights in syn1, we can calculate the error in the middle/hidden layer.

l1_delta:	This is the l1 error of the network scaled by the confidence. Again, it's almost identical to the l1_error except that confident errors are muted.


In [5]:
import numpy as np
X = np.array([ [0,0,1],[0,1,1],[1,0,1],[1,1,1] ])
y = np.array([[0,1,1,0]]).T
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1
for j in range(60000):
    l1 = 1/(1+np.exp(-(np.dot(X,syn0))))
    l2 = 1/(1+np.exp(-(np.dot(l1,syn1))))
    l2_delta = (y - l2)*(l2*(1-l2))
    l1_delta = l2_delta.dot(syn1.T) * (l1 * (1-l1))
    syn1 += l1.T.dot(l2_delta)
    syn0 += X.T.dot(l1_delta)
# this is a bit terse... let's break it aprat into a 
# few simple parts


In [6]:
import matplotlib.pyplot as plt


In [7]:
print(syn0)

[[-3.81573298 -0.99963235  6.05225847  8.34641714]
 [ 8.0128032   4.05312365  6.05628932 -4.40227592]
 [ 0.21437067 -0.75308567 -0.60513427  0.59387988]]


In [8]:
print(syn1)

[[ -9.17300316]
 [ -1.72625688]
 [ 16.15361643]
 [-10.51794185]]


In [9]:
import numpy as np
# sigmoid function
def nonlin(x,deriv=False):
    if(deriv == True):
        return(x*(1-x))
    return(1/(1+np.exp(-x)))



In [10]:
# input dataset
X = np.array([  [0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1] ])
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [12]:
# output dataset
y = np.array([[0,0,1,1]]).T
print(y)

[[0]
 [0]
 [1]
 [1]]


In [13]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

In [14]:
# initialize weights randomly with mean 0
syn0 = 2 * np.random.random((3,1)) - 1

In [17]:
for iter in range(10000):
    #forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    
    # how much did we miss?
    l1_error = y - l1
    
    # multiply how much we missed by the #
    # slope of sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    
    # update weights
    syn0 += np.dot(l0.T,l1_delta)

    
print("Output After Training:",l1)


Output After Training: [[ 0.00966449]
 [ 0.00786506]
 [ 0.99358898]
 [ 0.99211957]]


In [18]:
# 3 layer neural network
import numpy as np

def nolin(x,deriv=False):
    if(deriv == True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1] ])

y = np.array([[0,0,1,1]]).T

np.random.seed(1)

# randomly initialize our weights with mean 0
syn0 = 2* np.random.random((3,4))-1
syn1 = 2* np.random.random((4,1))-1
syn0,syn1

(array([[-0.16595599,  0.44064899, -0.99977125, -0.39533485],
        [-0.70648822, -0.81532281, -0.62747958, -0.30887855],
        [-0.20646505,  0.07763347, -0.16161097,  0.370439  ]]),
 array([[-0.5910955 ],
        [ 0.75623487],
        [-0.94522481],
        [ 0.34093502]]))

In [20]:
for j in range(60000):
    #feed forward through layers 0,1 and 2
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    l2 = nonlin(np.dot(l1,syn1))
    
    # how much did we miss?
    
    l2_error = y - l2
    
    if (j% 10000) == 0:
        print("Error" + str(np.mean(np.abs(l2_error))))
        
    # in what direction is the target value?
    # were we reallly sure? if so, don't change too much
    l2_delta = l2_error * nonlin(l2,deriv=True)
    
    # how much did each l1 value contribute to the 
    # l2 error (according to the weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # in what direction is the target l1? 
    # were we really sure? if so,don't change too much
    l1_delta = l1_error * nonlin(l1, deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)
    

Error0.468534325458
Error0.0050024267254
Error0.00345440546153
Error0.00278655701967
Error0.00239411550552
Error0.00212888526823


# not relevant

from matplotlib import pyplot
import numpy as np

border = 2
images_amount = 300
row_amount = 10
col_amount = 30
image_height = 28
image_width = 28


all_filter_image = np.zeros((row_amount*image_height + border*row_amount,
                             col_amount*image_width + border*col_amount))


for filter_num in range(images_amount):
    start_row = image_height*(filter_num / col_amount) +\
                (filter_num / col_amount + 1)*border

    end_row = start_row + image_height

    start_col = image_width*(filter_num % col_amount) +\
                (filter_num % col_amount + 1)*border

    end_col = start_col + image_width

    all_filter_image[start_row:end_row, start_col:end_col] = \
        all_filters[filter_num]

    print(start_row, end_row, start_col, end_col)


pyplot.imshow(all_filter_image)
pyplot.axis('off')
pyplot.set_cmap('spectral')
pyplot.colorbar()
#pyplot.savefig('repflds1.png')
http://stackoverflow.com/questions/30290506/neural-network-receptive-field-visualization-in-python